exclude: |
  ^fund/|
  ^assets/vendor/|
  ^node_modules/|
  ^venv/|
  ^.mypy_cache/|
  ^.ruff_cache/|
  ^coverage/|
  ^dist/|
  ^build/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.jsonc"]

