name: Submodule Sync

on:
    workflow_dispatch:
    schedule:
        - cron: '0 7 * * 1' # Every Monday 07:00 UTC

permissions:
    contents: write
    pull-requests: write

jobs:
    sync:
        uses: ryusoh/ci/.github/workflows/submodule-sync.yml@v1
        secrets: inherit
        with:
            depth: 0
            branch-name: chore/submodule-sync
            pr-title: 'chore(submodule): サブモジュールを最新に更新'
            pr-body: |
                `git submodule update --remote --recursive` による更新を反映します。
                `.gitmodules` に `branch = main` が設定されている場合、そのブランチを追従します。
            force-pr: ${{ github.event_name == 'schedule' }}
