name: Web CI

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      python-version:
        required: true
        type: string
      run-precommit:
        required: true
        type: boolean
      checkout-submodules:
        description: "Whether to checkout git submodules (recursive)"
        required: false
        default: true
        type: boolean
      deploy:
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: ${{ inputs['checkout-submodules'] && 'recursive' || 'false' }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs['python-version'] }}

      - name: Show versions
        run: |
          node -v
          npm -v
          python -V

      - name: Install Node deps (if package.json exists)
        id: node_install
        run: |
          if [ -f package.json ]; then npm ci; else echo "no-pkg"; fi

      - name: Check pre-commit config
        id: pc
        if: ${{ inputs['run-precommit'] }}
        shell: bash
        run: |
          if [ -f .pre-commit-config.yaml ]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install pre-commit
        if: ${{ inputs['run-precommit'] && steps.pc.outputs.present == 'true' }}
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        if: ${{ inputs['run-precommit'] && steps.pc.outputs.present == 'true' }}
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Skip pre-commit (config not found)
        if: ${{ inputs['run-precommit'] && steps.pc.outputs.present != 'true' }}
        run: echo ".pre-commit-config.yaml not found; skipping pre-commit"

      # (moved Node deps install before pre-commit)

      - name: Build/Test (no-op if absent)
        run: |
          if [ -f Makefile ]; then make -n build || true; fi

      - name: ESLint (prefer .ci-configs)
        run: |
          if [ -f .ci-configs/js/eslint.config.cjs ]; then
            npx --yes eslint . --config .ci-configs/js/eslint.config.cjs --max-warnings=0
          elif [ -n "${{ hashFiles('eslint.config.*') }}" ]; then
            npx --yes eslint . --max-warnings=0
          else
            echo "No ESLint config found; skipping"
          fi

      - name: Stylelint (prefer .ci-configs)
        run: |
          if [ -f .ci-configs/js/.stylelintrc.cjs ]; then
            IGNORE_ARG=""
            if [ -f .ci-configs/js/.stylelintignore ]; then IGNORE_ARG="--ignore-path .ci-configs/js/.stylelintignore"; fi
            npx --yes stylelint "**/*.css" --config .ci-configs/js/.stylelintrc.cjs $IGNORE_ARG --max-warnings=0 || true
          elif [ -n "${{ hashFiles('.stylelintrc.*') }}" ]; then
            npx --yes stylelint "**/*.css" --max-warnings=0 || true
          else
            echo "No Stylelint config found; skipping"
          fi

      - name: Prettier check (prefer .ci-configs)
        run: |
          if [ -f .ci-configs/js/.prettierrc.json ]; then
            IGNORE_ARG=""
            if [ -f .ci-configs/js/.prettierignore ]; then IGNORE_ARG="--ignore-path .ci-configs/js/.prettierignore"; fi
            npx --yes prettier -c . --config .ci-configs/js/.prettierrc.json $IGNORE_ARG
          elif [ -n "${{ hashFiles('.prettierrc*') }}" ]; then
            npx --yes prettier -c .
          else
            echo "No Prettier config found; skipping"
          fi

      - name: Deploy (placeholder)
        if: ${{ inputs.deploy }}
        run: echo "Deploy step controlled by caller workflow"
